### PR TITLE
Features ambr

### PR DESCRIPTION
**Pull request by DendoD96**
I @aligungr, this is the implementation. Let me know if there is something wrong or that you think is not done right.
I did some simple manual tests: basically with only one UE the AMBR is the minimum between APN_AMBR and UE_AMBR.

ue_limit
**UE_AMBR=2Mb/s APN_AMBR=3Mb/s**

apn_limit
**UE_AMBR=2Mb/s APN_AMBR=1Mb/s**

### CODE REVIEW

**Comment by aligungr** [comment]
@DendoD96 Thanks for the pull request. I appreciate your work. And here's my comments.

- Both `ueAggregateMaximumBitRate` and `sessionAggregateMaximumBitRate` are optional and it is possible that AMF does not include these values. So `computeUplinkAMBRInByte` and `computeDownlinkAMBRInByte` may raise NullPointerException. We should considered these values as infinite in these case.
- We should also consider the case that a UE using multiple PDU sessions simultaneously. For example if the UE has 2 sessions, total bandwidth of 2 sessions should be also limited by `ueAggregateMaximumBitRate`.

For example let's assume that the following configuration.

- UE-AMBR: 10 MB/s
- AMBR of PDU Session 1: 8 MB/s
- AMBR of PDU Session 2: 8 MB/s

In this case both sessions cannot exceed 8. That's we already have in your pull request. However the total bandwidth should also be limited by 10 MB/s. Therefore the bandwidth may be distributed as 5MB/s-5MB/s for example, or 8MB/s-2MB/s etc.

And also, as a result of this case, TokenBucket capacity may need to be changed over time. For example a UE can create or release multiple PDU sessions consecutively. Or both UE and session AMBR values may change over time by PDU Session Resource Modify or UE Context Modify commands.

I can merge the pull request as is, but I would be glad if you handle this scenario as well.

Thank you very much again for the work.

**Comment by DendoD96** [comment]
@aligungr i will handle this. We will merge the work when it is complete and correct. For the second answer: from what I understand from [TS 23.501](https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/16.06.00_60/ts_123501v160600p.pdf) UE_AMBR of your example should be the **min(10, 16) = 10**.  That is the minimum between the UE AMBR and the sum of the Session AMBR of all the PDU sessions associated with the UE. 
The mistake in my code (I believe) is to assign the bucket to a session PDU. It should be associated with a UE, after which the bitrate of the two sessions will be dynamically distributed based on the arrival of the messages, but it will never exceed the UE_AMBR value obtained through the formula.

**Comment by aligungr** [comment]
Exactly. If you associate the bucket with the UE, the problem is simply solved.

**Comment by DendoD96** [comment]
@aligungr Is it possible that the AMBRs change between sessions? 
For example: 
the user establishes a PDU session and the values are UE_AMBR = 2Mb/s APN_AMBR = 3Mb/s. Subsequently, the user establishes another PDU session and the parameters have become UE_AMBR: 3Mb/s APN_AMBR = 4Mb/s or null.

**Comment by DendoD96** [comment]
In order to fix the first answer `computeDownlinkAMBRInByte  `and `computeUplinkAMBRInByte ` manages NullPointerException and returns a Optional capacity. This is passed to a builder that returns the correct bucket: `SimpleTokenBucket` if optional is present, `FakeTokenBucket` otherwise. The bucket type is not relevant to the `RateLimiter` which is only interested in the `tryConsume` method. To do this, the new bucket must be evaluated when establishing each new PDU session. This is the reason I use the `put ` method on lines 159-161. To avoid the GC we can call `delete`.

In order to fix second, as we have already said, the bucket is assigned to UE instead to a specific PDU.

Bucket creation occurs only when a new PDU session is created.

**Comment by aligungr** [comment]
> 
> 
> @aligungr Is it possible that the AMBRs change between sessions?
> For example:
> the user establishes a PDU session and the values are UE_AMBR = 2Mb/s APN_AMBR = 3Mb/s. Subsequently, the user establishes another PDU session and the parameters have become UE_AMBR: 3Mb/s APN_AMBR = 4Mb/s or null.

Yes, more precisely UE AMBR or session AMBR values can change **any time** by "UE context modify" or "PDU Session Modify" messages issued by AMF.

---

I think `TokenBucket`, `SimpleTocketBucket`, `FakeTokenBucket`, `TocketBucketBuilder` classes are a little bit overkill. We should just use `TokenBucket` just like the last time you implemented. That was simple and efficient. We can handle infinite capacity with a slight modification I believe, for instance we can pass `-1` as capacity value while invoking the constructor of `TokenBucket`.

---

There is a minor problem in `computeDownlinkAMBRInByte` and `computeUplinkAMBRInByte`. The `stream()..reduce` always raises a NullPointerException if there exists at least one null value as `sessionAggregateMaximumBitRate`. For example if session 1 has null AMBR value, session 2 will also faces the NullPointerException since the reduce method simply iterate all items in the collection. I think we can use a simple for loop in this case.

**Comment by DendoD96** [comment]
Ok, I'll fix it. I think is correct to initialize/update the bucket when a new PDU is established, it will then be necessary to manage the modification messages. Right?
For the `computeDownlinkAMBRInByte ` and `computeUplinkAMBRInByte` i suppose there is also the possibility that all APN_AMBRs are 0.

**Comment by aligungr** [comment]
> Ok, I'll fix it. I think is correct to initialize/update the bucket when a new PDU is established, it will then be necessary to manage the modification messages. Right?

Yes, they are managed by NGAP layer, and we need to handle these cases. PDU session modify request is already not implemented yet, but we partially implemented UE context modify request. So we need to  initialize/update the bucket in UE context modification. See `NgapUeContextManagement.java` ln. 68

> For the computeDownlinkAMBRInByte and computeUplinkAMBRInByte i suppose there is also the possibility that all APN_AMBRs are 0.

Yes, it may be zero. Bit rates are in range (0..4,000,000,000,000) according to TS 38.413 9.3.1.58 and 9.3.1.4.

**Comment by DendoD96** [comment]
To do this we save the bucket in the UE context and we put the contexts also in the GtpTask?

**Comment by aligungr** [comment]
Not really. All layers must work fully independent of each other. We should not expose the buckets outside of the GtpTask.

Actually handling of NGAP UE context modification message is the easy part. We will just push an event from NgapTask to GtpTask.

Indeed your very first implemtation was almost complete. But we need to make the bucket capacity mutable.

**Comment by DendoD96** [comment]
Ok, i imagined it was necessary to propagate an event, but from the last message I did not understand. Anyway, I will return to a version similar to the initial one with the possibility of dynamically changing the capacity of the bucket and using -1 as capacity to model an infinite bucket

**Comment by DendoD96** [comment]
This implementation is similar to the first. The `computeAmbrInBit ` is implemented with for-loop and and manages `NullPointerException`. Bucket capacity can be changed and infinity bucket are modeled as buckets of capacity equals to -1. The only difference is that, for the moment, the bucket is created or updated when a new PDU session is established.

**Comment by aligungr** [comment]
Thanks it seems nice. I'll look at it in more detail tomorrow.

**Comment by DendoD96** [comment]
Ok, let me know. Sorry for the time i made you waste.

**Comment by aligungr** [comment]
Of course you didn't waste our time, you **saved** our time by implementing this feature :) Thanks for the contribution.

---

Actually try-catching NullPointerException is generally not a good idea.

Insead of:

```
try {
    foo.bar();
} catch (NullPointerException e) {
    fun();
}
```

Better to use, for example:

```
if (foo != null) {
    foo.bar();
} else {
    fun();
}
```

So let's fix `computeAmbrInBit` method.

For example in line ~201,

```
for (...) {

    if (pduSession.ueAggregateMaximumBitRate == null)
        continue;
    
    ...


    if (pduSession.sessionAggregateMaximumBitRate == null)
        continue;
}

```
etc. (Also we don't really need `getApnAmbr` and `getUeAmbr` function parameters in this case)

---

And I think it'll be ready to be merged after fixing this.

**Comment by DendoD96** [comment]
I replaced the `try/catch` with the `if`. The `getSessionLinkAmbr` and `getUeLinkAmbr` functions are used to avoid duplicating code. This makes it possible to separate the code to calculate the UE AMBR from the referenced link (DL or UL).

**Comment by aligungr** [comment]
Thanks for the contribution, I'm merging to `dev`. This feature will be available in the next release of UERANSIM.

**Comment by DendoD96** [comment]
Thanks for your time. In the future I would like to contribute again if it will be possible.

**Comment by aligungr** [comment]
Sure, thanks.

**Pull request merged**
